export const Key = 'c82ee8893088c842a8a9fe3f2d2a313a'
export const IMAGE_BASE_URL = 'https://image.tmdb.org/t/p/w500'
export const BASE_URL = 'https://api.themoviedb.org/3/'
//export const MOVIE_LISTURL = 'list/28?api_key='+Key+'&language=en-US'
export const MOVIE_LISTURL = 'movie/upcoming?api_key='+Key+'&language=en-US&page='
export const MOVIE_SEARCH = 'search/movie?api_key='+Key+'&query='
